sudo: false

language: php
php:
  - 'master'
  - '7.3'
  - '7.2'
  - '7.1'

git:
  depth: 1

addons:
  apt:
    packages:
      - re2c

matrix:
  fast_finish: true
  allow_failures:
    - php: 'master'

cache:
  apt: true
  timeout: 604800
  directories:
    - ${HOME}/.composer/cache
    - ${HOME}/.local/opt

env:
  global:
    - DEFAULT_COMPOSER_FLAGS="-n --no-ansi --no-progress --dev --prefer-dist --no-suggest"
    - ZEPHIR_VERSION="0.11.3"
    - PATH="${HOME}/.composer/vendor/bin:${PATH}"
    - PROJECT_ROOT=$(readlink -enq "$(dirname $0)/../")

branches:
  only:
    - master
    - development

install:
  - .ci/install-prereqs.sh
  - travis_retry composer install ${DEFAULT_COMPOSER_FLAGS}
  - travis_retry composer global require ${DEFAULT_COMPOSER_FLAGS} "phalcon/zephir:${ZEPHIR_VERSION}"
  - .ci/build.sh

script:
  - make help
  - make test PHP=$(phpenv which php)

after_failure:
  - .ci/after-failure.sh

notifications:
  email: false
