sudo: false

language: php
php:
  - 7.1

git:
  depth: 1

addons:
  apt:
    packages:
      - re2c

cache:
  apt: true
  timeout: 604800
  directories:
    - ${HOME}/.composer/cache
    - ${HOME}/.local/opt

env:
  global:
    - DEFAULT_COMPOSER_FLAGS="-n --no-ansi --no-progress --dev --prefer-dist --no-suggest"
    - ZEPHIR_VERSION="0.11.3"
    - PATH="${HOME}/bin:${HOME}/.composer/vendor/bin:${PATH}"

branches:
  only:
    - master

before_install:
  - export PHP_MAJOR="$(php -r 'echo phpversion();' | cut -d '.' -f 1)"
  - export PHP_MINOR="$(php -r 'echo phpversion();' | cut -d '.' -f 2)"
  - export PHP_VERNUM="$(`phpenv which php-config` --vernum)"

install:
  - .ci/install-prereqs.sh
  - travis_retry composer install ${DEFAULT_COMPOSER_FLAGS}
  - travis_retry composer global require ${DEFAULT_COMPOSER_FLAGS} "phalcon/zephir:${ZEPHIR_VERSION}"
  - .ci/build.sh

script:
  - make test PHP=$(phpenv which php)

after_failure:
  - .ci/after-failure.sh

notifications:
  email: false
