sudo: false

language: php
php:
  - 7.1

git:
  depth: 1

addons:
  apt:
    packages:
      - re2c

cache:
  apt: true
  timeout: 604800
  directories:
    - ${HOME}/.composer/cache
    - ${HOME}/.local/opt

branches:
  only:
    - master

before_install:
  - export PHP_MAJOR="$(`phpenv which php` -r 'echo phpversion();' | cut -d '.' -f 1)"
  - export PHP_MINOR="$(`phpenv which php` -r 'echo phpversion();' | cut -d '.' -f 2)"
  - export PHP_VERNUM="$(`phpenv which php-config` --vernum)"

install:
  - .ci/install-prereqs.sh

script:
  - true  

notifications:
  email: false
